// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js loads .env itself, but the Prisma CLI is a separate process and
// doesn't auto-load it — so load .env here. dotenv never overwrites a key
// already in process.env, so this gives .env priority over any env vars
// exported by the shell, matching Next.js's own precedence.
config({ path: ".env" });
config();

// Prisma Migrate's schema engine needs a real, unpooled connection — it
// doesn't work through a transaction-mode pooler (see lib/db.ts and
// .env.example). DIRECT_URL is that connection; it falls back to
// DATABASE_URL so local dev against an unpooled Postgres (e.g. the
// docker-compose database) needs nothing extra set.
//
// Note: `prisma generate` does NOT need a live connection, so the datasource
// URL is intentionally optional here. The `prisma migrate deploy` step in
// the build script will fail with a clear error if the URL is still missing
// at build time, giving us early feedback on misconfigured deployments.
const datasourceUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  ...(datasourceUrl
    ? { datasource: { url: datasourceUrl } }
    : {}),
});