// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js loads .env.local itself, but the Prisma CLI is a separate process
// and only auto-loads plain .env — so load .env.local explicitly here (it's
// the file actually used in this repo; see .env.example). dotenv never
// overwrites a key already in process.env, so loading .env.local first gives
// it priority over .env, matching Next.js's own precedence.
config({ path: ".env.local" });
config();

// Prisma Migrate's schema engine needs a real, unpooled connection — it
// doesn't work through a transaction-mode pooler (see lib/db.ts and
// .env.example). DIRECT_URL is that connection; it falls back to
// DATABASE_URL so local dev against an unpooled Postgres (e.g. the
// docker-compose database) needs nothing extra set.
const datasourceUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];

if (!datasourceUrl) {
  throw new Error(
    "DIRECT_URL or DATABASE_URL is not set. Copy .env.example to .env.local and configure it."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
